#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         2
bspc config window_gap          0
#bspc config window_gap          6
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focused_border_color "#b16286"
#picom --experimental-backend &
#xwallpaper --zoom /home/dawn/pix/peak.png &
#wal -i /home/dawn/pix/cloud.jpg &
$HOME/lemon.sh | lemonbar -p -F "#689d6a" -B "#000000"
#$HOME/.config/polybar/launch.sh &
